<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class HashtypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
                DB::table('hashtypes')->insert(['id' => '0','name' =>'MD5','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '10','name' =>'md5($pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20','name' =>'md5($salt.$pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '30','name' =>'md5(utf16le($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '40','name' =>'md5($salt.utf16le($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '50','name' =>'HMAC-MD5 (key = $pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '60','name' =>'HMAC-MD5 (key = $salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '100','name' =>'SHA1','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '110','name' =>'sha1($pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '120','name' =>'sha1($salt.$pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '130','name' =>'sha1(utf16le($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '140','name' =>'sha1($salt.utf16le($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '150','name' =>'HMAC-SHA1 (key = $pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '160','name' =>'HMAC-SHA1 (key = $salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '200','name' =>'MySQL323','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '300','name' =>'MySQL4.1/MySQL5','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '400','name' =>'phpass, WordPress (MD5)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '500','name' =>'md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '501','name' =>'Juniper IVE','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '600','name' =>'BLAKE2b-512','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '900','name' =>'MD4','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1000','name' =>'NTLM','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '1100','name' =>'Domain Cached Credentials (DCC), MS Cache','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '1300','name' =>'SHA-224','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1400','name' =>'SHA-256','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '1410','name' =>'sha256($pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1420','name' =>'sha256($salt.$pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1430','name' =>'sha256(utf16le($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1440','name' =>'sha256($salt.utf16le($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1450','name' =>'HMAC-SHA256 (key = $pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1460','name' =>'HMAC-SHA256 (key = $salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1500','name' =>'descrypt, DES (Unix), Traditional DES','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1600','name' =>'Apache $apr1$ MD5, md5apr1, MD5 (APR) 2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '1700','name' =>'SHA-512','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '1710','name' =>'sha512($pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1720','name' =>'sha512($salt.$pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1730','name' =>'sha512(utf16le($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1740','name' =>'sha512($salt.utf16le($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1750','name' =>'HMAC-SHA512 (key = $pass)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1760','name' =>'HMAC-SHA512 (key = $salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '1800','name' =>'sha512crypt $6$, SHA512 (Unix) 2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2100','name' =>'Domain Cached Credentials 2 (DCC2), MS Cache 2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2400','name' =>'Cisco-PIX MD5','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2410','name' =>'Cisco-ASA MD5','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2500','name' =>'WPA/WPA2 1','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2501','name' =>'WPA/WPA2 PMK 14','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '2600','name' =>'md5(md5($pass))','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '3000','name' =>'LM','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '3100','name' =>'Oracle H: Type (Oracle 7+), DES(Oracle)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '3200','name' =>'bcrypt $2*$, Blowfish (Unix)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '3710','name' =>'md5($salt.md5($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '3800','name' =>'md5($salt.$pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '3910','name' =>'md5(md5($pass).md5($salt))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4010','name' =>'md5($salt.md5($salt.$pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4110','name' =>'md5($salt.md5($pass.$salt))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4300','name' =>'md5(strtoupper(md5($pass)))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4400','name' =>'md5(sha1($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4500','name' =>'sha1(sha1($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4520','name' =>'sha1($salt.sha1($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4700','name' =>'sha1(md5($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4710','name' =>'sha1(md5($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4800','name' =>'iSCSI CHAP authentication, MD5(CHAP) 7','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '4900','name' =>'sha1($salt.$pass.$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5100','name' =>'Half MD5','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5200','name' =>'Password Safe v3','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5300','name' =>'IKE-PSK MD5','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5400','name' =>'IKE-PSK SHA1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5500','name' =>'NetNTLMv1 / NetNTLMv1+ESS','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '5600','name' =>'NetNTLMv2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '5700','name' =>'Cisco-IOS type 4 (SHA256)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '5800','name' =>'Samsung Android Password/PIN','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6000','name' =>'RIPEMD-160','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6100','name' =>'Whirlpool','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6300','name' =>'AIX {smd5}','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6400','name' =>'AIX {ssha256}','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6500','name' =>'AIX {ssha512}','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6600','name' =>'1Password, agilekeychain','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6700','name' =>'AIX {ssha1}','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '6800','name' =>'LastPass + LastPass sniffed4','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '7100','name' =>'OSX v10.8+ (PBKDF2-SHA512)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '7200','name' =>'GRUB','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '7300','name' =>'IPMI2 RAKP HMAC-SHA1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '7400','name' =>'sha256crypt $5$, SHA256 (Unix) 2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '7500','name' =>'Kerberos 5 AS-REQ Pre-Auth etype 23','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '7700','name' =>'SAP CODVN B (BCODE)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '7701','name' =>'SAP CODVN B (BCODE) mangled from RFC_READ_TABLE','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '7800','name' =>'SAP CODVN F/G (PASSCODE)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '7801','name' =>'SAP CODVN F/G (PASSCODE) mangled from RFC_READ_TABLE','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '7900','name' =>'Drupal7','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '8000','name' =>'Sybase ASE','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8100','name' =>'Citrix NetScaler','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8200','name' =>'1Password, cloudkeychain','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8300','name' =>'DNSSEC (NSEC3)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8400','name' =>'WBB3 (Woltlab Burning Board)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8500','name' =>'RACF','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8800','name' =>'Android FDE <= 4.3','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '8900','name' =>'scrypt','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '9000','name' =>'Password Safe v2','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '9100','name' =>'Lotus Notes/Domino 8','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '9200','name' =>'Cisco-IOS $8$ (PBKDF2-SHA256)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '9300','name' =>'Cisco-IOS $9$ (scrypt)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '9400','name' =>'MS Office 2007','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '9500','name' =>'MS Office 2010','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '9600','name' =>'MS Office 2013','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '9900','name' =>'Radmin2','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '10000','name' =>'Django (PBKDF2-SHA256)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '10100','name' =>'SipHash','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '10200','name' =>'CRAM-MD5','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '10300','name' =>'SAP CODVN H (PWDSALTEDHASH) iSSHA-1','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '10800','name' =>'SHA-384','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '10900','name' =>'PBKDF2-HMAC-SHA256','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '11000','name' =>'PrestaShop','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '11100','name' =>'PostgreSQL CRAM (MD5)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '11200','name' =>'MySQL CRAM (SHA1)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '11400','name' =>'SIP digest authentication (MD5)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '11500','name' =>'CRC32 5','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '11600','name' =>'7-Zip','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '11900','name' =>'PBKDF2-HMAC-MD5','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12000','name' =>'PBKDF2-HMAC-SHA1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12100','name' =>'PBKDF2-HMAC-SHA512','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12200','name' =>'eCryptfs','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12300','name' =>'Oracle T: Type (Oracle 12+)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12400','name' =>'BSDiCrypt, Extended DES','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12500','name' =>'RAR3-hp','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12600','name' =>'ColdFusion 10+','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12800','name' =>'MS-AzureSync PBKDF2-HMAC-SHA256','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '12900','name' =>'Android FDE (Samsung DEK)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '13000','name' =>'RAR5','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '13100','name' =>'Kerberos 5 TGS-REP ','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '13200','name' =>'AxCrypt','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '13300','name' =>'AxCrypt in-memory SHA1 13','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '13400','name' =>'KeePass 1/2','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '13500','name' =>'PeopleSoft PS_TOKEN','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '13600','name' =>'WinZip','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '13900','name' =>'OpenCart','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '14000','name' =>'DES (PT = $salt, key = $pass) 8','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '14100','name' =>'3DES (PT = $salt, key = $pass) 9','salted'=>FALSE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '14400','name' =>'sha1(CX)','salted'=>FALSE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '14600','name' =>'LUKS 10','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '14700','name' =>'iTunes backup < 10.0 11','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '14800','name' =>'iTunes backup >= 10.0 11','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '14900','name' =>'Skip32 (PT = $salt, key = $pass) 12','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '15000','name' =>'FileZilla Server >= 0.9.55','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '15100','name' =>'Juniper/NetBSD sha1crypt','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '15400','name' =>'ChaCha20 20','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '15500','name' =>'JKS Java Key Store Private Keys (SHA1)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16000','name' =>'Tripcode','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16100','name' =>'TACACS+','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16200','name' =>'Apple Secure Notes','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16400','name' =>'CRAM-MD5 Dovecot','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16500','name' =>'JWT (JSON Web Token)','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '16600','name' =>'Electrum Wallet (Salt-Type 1-3)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16700','name' =>'FileVault 2','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16800','name' =>'WPA-PMKID-PBKDF2 1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16801','name' =>'WPA-PMKID-PMK 15','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '16900','name' =>'Ansible Vault','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17300','name' =>'SHA3-224','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17400','name' =>'SHA3-256','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17500','name' =>'SHA3-384','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17600','name' =>'SHA3-512','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17700','name' =>'Keccak-224','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17800','name' =>'Keccak-256','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '17900','name' =>'Keccak-384','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18000','name' =>'Keccak-512','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18100','name' =>'TOTP (HMAC-SHA1)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18200','name' =>'Kerberos 5 AS-REP','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '18300','name' =>'Apple File System (APFS)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18500','name' =>'sha1(md5(md5($pass)))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18700','name' =>'Java Object hashCode()','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18800','name' =>'Blockchain, My Wallet, Second Password (SHA256)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '18900','name' =>'Android ','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '19000','name' =>'QNX /etc/shadow (MD5)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '19100','name' =>'QNX /etc/shadow (SHA256)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '19200','name' =>'QNX /etc/shadow (SHA512)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '19500','name' =>'Ruby on Rails Restful-Authentication','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '19600','name' =>'Kerberos 5 TGS-REP etype 17 ','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '19700','name' =>'Kerberos 5 TGS-REP etype 18 ','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '19800','name' =>'Kerberos 5, etype 17, Pre-Auth','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '19900','name' =>'Kerberos 5, etype 18, Pre-Auth','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '20200','name' =>'Python passlib pbkdf2-sha512','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20300','name' =>'Python passlib pbkdf2-sha256','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20400','name' =>'Python passlib pbkdf2-sha1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20500','name' =>'PKZIP Master Key','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20510','name' =>'PKZIP Master Key (6 byte optimization) 17','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20600','name' =>'Oracle Transportation Management (SHA256)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20710','name' =>'sha256(sha256($pass).$salt)','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20800','name' =>'sha256(md5($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '20900','name' =>'md5(sha1($pass).md5($pass).sha1($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21000','name' =>'BitShares v0.x - sha512(sha512_bin(pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21100','name' =>'sha1(md5($pass.$salt))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21200','name' =>'md5(sha1($salt).md5($pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21300','name' =>'md5($salt.sha1($salt.$pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21400','name' =>'sha256(sha256_bin(pass))','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '21500','name' =>'SolarWinds Orion','salted'=>TRUE,'enabled'=>TRUE]);
DB::table('hashtypes')->insert(['id' => '21600','name' =>'Web2py pbkdf2-sha512','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '22000','name' =>'WPA-PBKDF2-PMKID+EAPOL 1','salted'=>TRUE,'enabled'=>FALSE]);
DB::table('hashtypes')->insert(['id' => '22001','name' =>'WPA-PMK-PMKID+EAPOL 18','salted'=>TRUE,'enabled'=>FALSE]);

    }
}
